version: '3'
services:
  db: 
    container_name: mysql-todolist
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: todo
    ports:
      - 3306:3306
    networks:
      - mysql-ntw

networks:
  mysql-ntw:
    external: true
      